# Generated by Django 3.2.19 on 2023-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_transaction',
            field=models.CharField(max_length=400, verbose_name='Последняя транзакция'),
        ),
    ]
