# Generated by Django 3.2.19 on 2023-07-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_last_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='balance',
        ),
    ]
