# Generated by Django 3.2.19 on 2023-07-26 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_quantity_stock_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='balance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
