# Generated by Django 3.2.19 on 2023-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
