version: "3"
services:
  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
      - static_volume:/FruitShop/static
      - media_volume:/FruitShop/media
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    restart: always
    command: make setup
    volumes:
      - static_volume:/FruitShop/static
      - media_volume:/FruitShop/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  celery:
    build: .
    command: celery -A FruitShop.celery worker -l INFO -Q buy,sell,test,joke -B
    volumes:
      - .:/FruitShop/
    env_file:
      - ./.env
    depends_on:
      - db
      - web
      - redis
  redis:
    image: redis
volumes:
  static_volume:
  media_volume:
  postgres_data: