# Generated by Django 3.2.19 on 2023-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Банк')),
                ('file', models.FileField(upload_to='file/', verbose_name='Декларация')),
            ],
        ),
    ]
