# Generated by Django 3.2.19 on 2023-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(default='user', max_length=100, verbose_name='Имя'),
        ),
    ]
