# Generated by Django 3.2.19 on 2023-07-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Время'),
        ),
    ]
