# Generated by Django 3.2.19 on 2023-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
