# Generated by Django 3.2.19 on 2023-07-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_fruit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
