# Generated by Django 3.2.19 on 2023-07-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_fruit_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=10, verbose_name='Ответ')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('status', models.BooleanField()),
                ('fruit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.fruit')),
            ],
        ),
    ]
