# Generated by Django 3.2.19 on 2023-07-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('transaction', '0007_alter_transaction_fruit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fruit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
