# Generated by Django 3.2.19 on 2023-07-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_fruit_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
